# arxivの学問領域の指定
#cat:physics.acc-ph OR cat:physics.atom-ph OR cat:physics.pop-ph
subject: 'cat:physics.* OR cat:astro-ph.*'
# 検索キーワード
keywords:
        accelerator: 3
        cosmic ray: 1
        LHC: 1
        baem: 1
        Betatron: 2
        synchrotron: 2
        Storage Rings: 1
        muon: 1
        mass spectrometry: 1
        hypernucleus : 2
        hyperon : 2
        hadron : 2
        tandem: 1
        TPC: 3
        GEM: 3
        Glass GEM: 3
# 通知の閾値
score_threshold: 0
